# Generated by Django 3.2.2 on 2021-12-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='setting_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
