# Generated by Django 4.0.2 on 2022-04-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('license_name', models.TextField(blank=True, null=True)),
                ('license_client_id', models.TextField(blank=True, null=True)),
                ('license_private_key', models.TextField(blank=True, null=True)),
                ('license_created_at', models.DateTimeField(auto_now_add=True)),
                ('license_expired_at', models.DateTimeField(auto_now_add=True)),
                ('license_status', models.BooleanField(blank=True, default=0, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'license',
            },
        ),
    ]
