# Generated by Django 4.0.2 on 2022-04-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='license_client_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='license_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
