version: 2.1

jobs:
  tests:
    docker:
      - image: circleci/python:3.6.4
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
          POSTGRES_DB: myboard
          MYBOARD_DEBUG: False
          MYBOARD_ALLOWED_HOST: "*"
          MYBOARD_HOSTNAME: myboard
          MYBOARD_USERNAME: root
          MYBOARD_PASSWORD: root
          MYBOARD_HOST: 127.0.0.1
          MYBOARD_PORT: 3306
          MYBOARD_STATIC_URL: /static/
          MYBOARD_API_URL: http://localhost:8000
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install Dependencies
          command: |
            pip install --user -r requirements.txt
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
      - run: python manage.py test

workflows:
  main:
    jobs:
      - tests