# Generated by Django 4.0.2 on 2022-05-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentReminder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myboardpaymentreminder',
            name='payment_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='myboardpaymentreminder',
            name='payment_price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
