# Generated by Django 4.0 on 2021-12-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='S3BucketManagement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bucket_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bucket_region', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 's3_bucket_management',
            },
        ),
    ]
