# Generated by Django 4.0 on 2021-12-10 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s3', '0002_s3bucketmanagement_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='s3bucketmanagement',
            name='is_deleted',
        ),
    ]
