# Generated by Django 4.0 on 2021-12-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s3', '0003_remove_s3bucketmanagement_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='S3FileManagement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_key', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 's3_file_management',
            },
        ),
        migrations.CreateModel(
            name='S3FolderManagement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('folder_name', models.CharField(blank=True, max_length=255, null=True)),
                ('folder_key', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 's3_folder_management',
            },
        ),
    ]
