# Generated by Django 4.0 on 2021-12-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s3', '0006_alter_s3foldermanagement_folder_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='s3filemanagement',
            name='bucket_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
