# Generated by Django 3.2.2 on 2021-12-12 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s3', '0007_s3filemanagement_bucket_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='s3filemanagement',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='s3.s3foldermanagement'),
        ),
    ]
