# Generated by Django 3.2.2 on 2021-12-13 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s3', '0008_s3filemanagement_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='s3filemanagement',
            name='bucket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='s3.s3bucketmanagement'),
        ),
        migrations.AddField(
            model_name='s3foldermanagement',
            name='bucket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='s3.s3bucketmanagement'),
        ),
    ]
