# Generated by Django 4.0 on 2022-01-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExLabels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label_name', models.TextField(blank=True, null=True)),
                ('label_slug', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('lable_type', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ex_labels',
            },
        ),
    ]
