# Generated by Django 4.0 on 2022-01-05 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exlabels',
            old_name='lable_type',
            new_name='label_type',
        ),
    ]
